from dataclasses import dataclass, is_dataclass, fields, field
from typing import List, Optional, Dict, Any
import numpy as np

from enums import get_impact_to_profile_map, Char as CharEnum
from helpers import fast_deepcopy, tse_id_to_dict

# Build the impact-to-profile mapping at module level for reuse.
_IMPACT_TO_PROFILE_MAP = get_impact_to_profile_map(CharEnum())


# 2-Player Refactor: Reserved actor ID for exogenous event sources.
# Exogenous events are not generated by DSM decision cycles; they are
# injected into the World State Timeline by the pre-processor.
EXOGENOUS_ACTOR_ID = -99


@dataclass
class ExogenousEventDefinition:
    """
    Defines a third-party event that enters the simulation through the
    Exogenous Event Mechanism rather than a full DSM decision cycle.

    See Multi-Actor Refactor Spec v0.1, Section 4.2.
    """
    event_id: str
    event_label: str
    source_actor_label: str
    relationship_tag: int  # RelationshipTag enum value (Ally=0, Adversary=1, Neutral=2)
    characteristics_vector: List[float]  # 7x1: Severity, Clarity, Irreversibility, etc.
    trigger_type: int  # ExogenousTriggerType enum value (Scripted=0, Conditional=1, Stochastic=2)
    trigger_config: Dict[str, Any]
    goal_impact_override: Optional[List[float]] = None  # (num_goals x 1) or None
    coa_id: Optional[int] = None
    affects_coalition: Optional[Dict[str, Any]] = None


@dataclass
class ActionSequenceData:
    actor_id: int
    coa_id_list: List[int]
    coa_characteristics_list: List[np.ndarray]

@dataclass
class EventData:
    """
    action_sequence: An ordered sequence of actions observed from one or more other actors.
            List elements should be tuples of the form (actor_index, action_vector),
            where actor_index is the index of the actor in the system (0-indexed) and action_vector is a numpy array

    """
    event_id: str
    acting_actor_id: int
    initial_actor_data: dict = field(metadata={"json_exclude": True})
    initial_system_data: dict = field(metadata={"json_exclude": True})
    initial_action_sequence: List[ActionSequenceData]
    event_data: dict
    resulting_action_sequence: ActionSequenceData
    resulting_actor_data: dict = field(metadata={"json_exclude": True})
    resulting_actor_impacts: np.ndarray = field(metadata={"json_exclude": True})

@dataclass
class StepData:
    step_id: str
    name: str
    initial_actors_data: list = field(metadata={"json_exclude": True})
    events: List[EventData]
    resulting_action_sequence: List[ActionSequenceData]
    resulting_system_data: dict = field(metadata={"json_exclude": True})
    resulting_actors_data: list = field(metadata={"json_exclude": True})

    def __post_init__(self):
        if self.name is None or self.name == "":
            self.name = self.step_id

    def actor_data(self, actor_id: int) -> dict | None:
        if actor_id < len(self.resulting_actors_data):
            return self.resulting_actors_data[actor_id]
        return None

    def finalize_step(self):
        if self.events and len(self.events) > 0:
            self.resulting_action_sequence = [e.resulting_action_sequence for e in self.events]

            # Update actors data
            self.resulting_actors_data = fast_deepcopy(self.initial_actors_data)
            actor_impacts = np.zeros_like(self.events[0].resulting_actor_impacts)
            for event in self.events:
                self.resulting_actors_data[event.acting_actor_id] = event.resulting_actor_data
                actor_impacts += event.resulting_actor_impacts

            # Route each impact dimension to the correct Char index in the profile.
            for idx in range(len(self.resulting_actors_data)):
                spv = self.resulting_actors_data[idx]["Self-Profile-Vector"]
                for impact_dim, profile_dim in _IMPACT_TO_PROFILE_MAP.items():
                    impact_value = actor_impacts[idx, impact_dim, 0]
                    spv[profile_dim, 0] = np.clip(
                        spv[profile_dim, 0] * (1 + impact_value), 0.0, 1.0
                    )
                self.resulting_actors_data[idx]["Self-Profile-Vector"] = spv

            # Apply credibility effects from commitment violations/fulfillments.
            # Dual-write: update both the acting actor's SPV[Credibility]
            # (self-awareness) AND the adversary's OPV[Credibility] for the
            # acting actor (reputation update). The perception pipeline
            # (Stage 1 → Stage 4 learning) updates OPV from action-level
            # Base Input Vectors, not actor-level state, so without the
            # direct OPV write the adversary would never observe the
            # credibility change.
            _char_enum = CharEnum()
            _credibility_idx = (
                _char_enum['Credibility'] if 'Credibility' in _char_enum else None
            )
            if _credibility_idx is not None:
                num_actors = len(self.resulting_actors_data)
                for event in self.events:
                    actor_id = event.acting_actor_id
                    delta = event.event_data.get("Self-Credibility-Delta", 0.0)
                    if delta != 0.0:
                        # Leg 1: Acting actor's own SPV (self-awareness)
                        spv = self.resulting_actors_data[actor_id]["Self-Profile-Vector"]
                        spv[_credibility_idx, 0] = float(np.clip(
                            spv[_credibility_idx, 0] + delta, 0.0, 1.0
                        ))

                        # Leg 2: Adversary's OPV for the acting actor (reputation)
                        # 2-Player: the adversary is the other non-exogenous actor.
                        adversary_id = 1 - actor_id
                        if 0 <= adversary_id < num_actors:
                            opv = self.resulting_actors_data[adversary_id]["Other-Profile-Vector"]
                            opv[_credibility_idx, 0] = float(np.clip(
                                opv[_credibility_idx, 0] + delta, 0.0, 1.0
                            ))

            # Update system data
            # 2-Player: Relationship scores are now per-actor scalars, persisted in
            # actor_data (not system_data). Each event updates its own actor's score
            # via resulting_actor_data, so no system-level merge is needed.
            self.resulting_system_data = fast_deepcopy(self.events[0].initial_system_data)

@dataclass
class TurnData:
    turn_id: str
    name: str
    steps: List[StepData]

    def __post_init__(self):
        if self.name is None or self.name == "":
            self.name = self.turn_id

    def actor_data(self, actor_id: int) -> dict | None:
        if self.steps and len(self.steps) == 0:
            return None
        return self.steps[-1].actor_data(actor_id)

    def final_system_data(self) -> dict | None:
        if self.steps and len(self.steps) > 0:
            return self.steps[-1].resulting_system_data
        return None

    def final_actors_data(self) -> List[dict] | None:
        if self.steps and len(self.steps) > 0:
            return self.steps[-1].resulting_actors_data
        return None

    def final_action_sequence(self) -> List[ActionSequenceData] | None:
        if self.steps and len(self.steps) > 0:
            for step in reversed(self.steps):
                if step.resulting_action_sequence and len(step.resulting_action_sequence) > 0:
                    return step.resulting_action_sequence
        return None

@dataclass
class SimulationData:
    sim_id: str
    name: str
    turns: List[TurnData]
    initial_system_data: dict = field(metadata={"json_exclude": True})
    initial_actors_data: List[dict] = field(metadata={"json_exclude": True})
    initial_action_sequence: List[ActionSequenceData] = field(metadata={"json_exclude": True})
    scenario_init_data_id: str = field(metadata={"json_exclude": True})
    scenario_config: dict = field(metadata={"json_exclude": True})

    def action_sequence_before(self, tse_id: str) -> List[ActionSequenceData]:
        """
        Retrieves the action sequence before a given turn/step/event.
        :param tse_id: An ID for either a turn, step, or event, in the format "tX", "tXsY", or "tXsYeZ",
        :return:
        """
        step_idx = None
        turn_idx = None

        id_dict = tse_id_to_dict(tse_id)
        if "step_id" in id_dict:
            step_idx = id_dict["step_id"]
        if "turn_id" in id_dict:
            turn_idx = id_dict["turn_id"]

        if turn_idx is None:
            return self.initial_action_sequence
        if step_idx is not None and step_idx != 0:
            action_sequence = self.turns[turn_idx].steps[step_idx-1].resulting_action_sequence
            return action_sequence
        if turn_idx > 0:
            return self.turns[turn_idx-1].final_action_sequence()

        return self.initial_action_sequence

    def system_data_before(self, tse_id: str) -> dict:
        """
        Retrieves the system data before a given turn/step/event.
        :param tse_id: An ID for either a turn, step, or event, in the format "tX", "tXsY", or "tXsYeZ",
        :return:
        """
        step_idx = None
        turn_idx = None

        id_dict = tse_id_to_dict(tse_id)
        if "step_id" in id_dict:
            step_idx = id_dict["step_id"]
        if "turn_id" in id_dict:
            turn_idx = id_dict["turn_id"]

        if turn_idx is None:
            return self.initial_system_data
        if step_idx is not None and step_idx != 0:
            system_data = self.turns[turn_idx].steps[step_idx-1].resulting_system_data
            return system_data
        if turn_idx > 0:
            return self.turns[turn_idx-1].final_system_data()

        return self.initial_system_data

    def actor_data_before(self, actor_id: int, tse_id: str) -> dict:
        """
        Retrieves the actor data for a specific actor before a given turn/step/event.
        :param actor_id:
        :param tse_id: An ID for either a turn, step, or event, in the format "tX", "tXsY", or "tXsYeZ",
        :return:
        """
        step_idx = None
        turn_idx = None

        id_dict = tse_id_to_dict(tse_id)

        if "step_id" in id_dict:
            step_idx = id_dict["step_id"]

        if "turn_id" in id_dict:
            turn_idx = id_dict["turn_id"]
    
        if turn_idx is None:
            return self.initial_actors_data[actor_id]
    
        # Check previous steps in the current turn
        if step_idx is not None and step_idx > 0:
            for s_idx in reversed(range(step_idx)):
                actor_data = self.turns[turn_idx].steps[s_idx].actor_data(actor_id)
                if actor_data is not None:
                    return actor_data
    
        # Check previous turns
        if turn_idx > 0:
            for t_idx in reversed(range(turn_idx)):
                actor_data = self.turns[t_idx].actor_data(actor_id)
                if actor_data is not None:
                    return actor_data

        return self.initial_actors_data[actor_id]

    def actors_data_before(self, tse_id: str) -> List[dict]:
        """
        Retrieves all actors data before a given turn/step/event.
        :param tse_id: An ID for either a turn, step, or event, in the format "tX", "tXsY", or "tXsYeZ",
        :return:
        """
        step_idx = None
        turn_idx = None

        id_dict = tse_id_to_dict(tse_id)
        if "step_id" in id_dict:
            step_idx = id_dict["step_id"]
        if "turn_id" in id_dict:
            turn_idx = id_dict["turn_id"]

        if turn_idx is None:
            return self.initial_actors_data
    
        # Check previous steps in the current turn
        if step_idx is not None and step_idx > 0:
            for s_idx in reversed(range(step_idx)):  # FIX: range(step_idx) not range(step_idx - 1)
                actors_data = self.turns[turn_idx].steps[s_idx].resulting_actors_data
                if actors_data is not None:
                    return actors_data
    
        # Check previous turns
        if turn_idx > 0:
            for t_idx in reversed(range(turn_idx)):  # FIX: range(turn_idx) not range(turn_idx - 1)
                actors_data = self.turns[t_idx].final_actors_data()
                if actors_data is not None:
                    return actors_data
    
        return self.initial_actors_data

    def latest_actor_data(self, actor_id: int) -> dict | None:
        for turn in reversed(self.turns):
            actor_data = turn.actor_data(actor_id)
            if actor_data is not None:
                return actor_data
        for actor_data in self.initial_actors_data:
            if actor_data['actor_id'] == actor_id:
                return actor_data
        return None

    def latest_actors_data(self) -> List[dict]:
        for turn in reversed(self.turns):
            actors_data = turn.final_actors_data()
            if actors_data is not None:
                return actors_data
        return self.initial_actors_data

    def latest_system_data(self) -> dict | None:
        for turn in reversed(self.turns):
            system_data = turn.final_system_data()
            if system_data is not None:
                return system_data
        return self.initial_system_data


def from_dict(cls, data):
    if not is_dataclass(cls):
        raise TypeError(f"{cls} is not a dataclass type")

    kwargs = {}
    for f in fields(cls):
        val = data.get(f.name)
        if is_dataclass(f.type) and isinstance(val, dict):
            kwargs[f.name] = from_dict(f.type, val)
        elif (getattr(f.type, "__origin__", None) is list and
              len(getattr(f.type, "__args__", [])) == 1 and
              is_dataclass(f.type.__args__[0])):
            # handle List[SomeDataclass]
            subcls = f.type.__args__[0]
            kwargs[f.name] = [from_dict(subcls, v) if isinstance(v, dict) else v for v in val]
        else:
            kwargs[f.name] = val
    return cls(**kwargs)

def to_builtin(obj, *, drop_callables=True, drop_private=True):
    # dataclasses: only declared fields (methods/properties are not included)
    if is_dataclass(obj):
        out = {}
        for f in fields(obj):
            name = f.name
            if drop_private and name.startswith("_"):
                continue
            if f.metadata.get("json_exclude", False):
                continue
            val = getattr(obj, name)
            if drop_callables and callable(val):
                continue
            out[name] = to_builtin(val, drop_callables=drop_callables, drop_private=drop_private)
        return out

    # numpy arrays/scalars
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, np.generic):  # np.int64, np.float32, etc.
        return obj.item()

    # containers
    if isinstance(obj, dict):
        out = {}
        for k, v in obj.items():
            if drop_private and isinstance(k, str) and k.startswith("_"):
                continue
            if drop_callables and callable(v):
                continue
            out[to_builtin(k, drop_callables=drop_callables, drop_private=drop_private)] = \
                to_builtin(v, drop_callables=drop_callables, drop_private=drop_private)
        return out

    if isinstance(obj, (list, tuple, set)):
        return [to_builtin(x, drop_callables=drop_callables, drop_private=drop_private) for x in obj]

    # Plain class instances (e.g. ContinuationReview, WorldStateTimeline):
    # serialize via __dict__ so Flask's JSON encoder doesn't choke on them.
    # Also inspect @property descriptors on the class so that objects with
    # only private backing attributes (like WorldStateTimeline._records)
    # still expose their public properties (like .records) in the output.
    if hasattr(obj, '__dict__') and not isinstance(obj, type):
        out = {}
        for k, v in obj.__dict__.items():
            if drop_private and k.startswith("_"):
                continue
            if drop_callables and callable(v):
                continue
            out[k] = to_builtin(v, drop_callables=drop_callables, drop_private=drop_private)

        # Include @property descriptors from the class hierarchy.
        for cls in type(obj).__mro__:
            for attr_name, attr_val in vars(cls).items():
                if isinstance(attr_val, property) and attr_name not in out:
                    if drop_private and attr_name.startswith("_"):
                        continue
                    try:
                        val = attr_val.fget(obj)
                        if drop_callables and callable(val):
                            continue
                        out[attr_name] = to_builtin(
                            val, drop_callables=drop_callables,
                            drop_private=drop_private,
                        )
                    except Exception:
                        pass  # skip properties that raise
        return out

    # everything else (ints, floats, str, bool, None, etc.)
    return obj
